import React from 'react';

import { useSelector } from 'react-redux';

import GeneralCard from './GeneralCard';

export const EmployeeScore = (props) => {

    const score = useSelector((state) => {

        const feedbacks = state.feedbackItems;

        var doctor_scores = 0;
        var num_feedbacks = 0;
        var staff_scores = 0;
        for (let i = 0; i < feedbacks.length; i++) {
            const feedbackItem = feedbacks[i];
            var totaldoctorentries = 0;
            var totalstaffentries = 0;
           try {
            if(props.departmentfilterval !== "All"){
                if(feedbackItem.Patient.Ward === props.departmentfilterval){
                    totalstaffentries =( feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1===6?0:1) : 0) + 

                    ( feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2===6?0:1) : 0)+ 
        
                    ( feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3===6?0:1) : 0)+ 
        
                    ( feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4===6?0:1) : 0)+ 
        
                    ( feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5===6?0:1) : 0) ;
                    
                    var staffScore = 0;
                    totalstaffentries === 0 ? staffScore = 0 :  staffScore = Math.round(((feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1) : 0)
        
                    +(feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2) : 0)
        
                    +(feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3) : 0)
        
                    +(feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4) : 0)
        
                    +(feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5) : 0)
        
                    )/(totalstaffentries)*100)/100;
                    staff_scores = staff_scores + staffScore;
                    if (totalstaffentries !== 0) num_feedbacks =num_feedbacks + 1;

                     totaldoctorentries =( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1===6?0:1) : 0) + 

                    ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2===6?0:1) : 0)+ 

                    ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3===6?0:1) : 0)+ 

                    ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4===6?0:1) : 0)+ 

                    ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5===6?0:1) : 0) ;
                    
                    var doctorScore = 0;
                    totaldoctorentries === 0 ? doctorScore = 0 :  doctorScore = Math.round(((feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1) : 0)

                    +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2) : 0)

                    +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3) : 0)

                    +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4) : 0)

                    +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5) : 0)

                    )/(totaldoctorentries)*100)/100;
                    doctor_scores = doctor_scores + doctorScore;
                    
        
                   
                    if (totaldoctorentries !== 0) num_feedbacks =num_feedbacks + 1;
                }
            } else{
                totalstaffentries =( feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1===6?0:1) : 0) + 

                ( feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2===6?0:1) : 0)+ 
    
                ( feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3===6?0:1) : 0)+ 
    
                ( feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4===6?0:1) : 0)+ 
    
                ( feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5===6?0:1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5 ?  (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5===6?0:1) : 0) ;
                
                var staffScore = 0;
                totalstaffentries === 0 ? staffScore = 0 :  staffScore = Math.round(((feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffcourtesyrating1): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffempathyrating1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffexplanationrating1): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffskillsrating1) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance1.staffprofessionalrating1) : 0)
    
                +(feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffcourtesyrating2): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffempathyrating2): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffexplanationrating2): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffskillsrating2) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance2.staffprofessionalrating2) : 0)
    
                +(feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffcourtesyrating3): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffempathyrating3): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffexplanationrating3): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffskillsrating3) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance3.staffprofessionalrating3) : 0)
    
                +(feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffcourtesyrating4): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffempathyrating4): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffexplanationrating4): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffskillsrating4) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance4.staffprofessionalrating4) : 0)
    
                +(feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffcourtesyrating5): 0 )+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffempathyrating5): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffexplanationrating5): 0) + (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffskillsrating5) : 0)+ (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5 ? (feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5=== 6? 0:feedbackItem.survey.generalsurvey.staffrating.staffperformance5.staffprofessionalrating5) : 0)
    
                )/(totalstaffentries)*100)/100;
                staff_scores = staff_scores + staffScore;
                if (totalstaffentries !== 0) num_feedbacks =num_feedbacks + 1;

                 totaldoctorentries =( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1===6?0:1) : 0) + 

                ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2===6?0:1) : 0)+ 

                ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3===6?0:1) : 0)+ 

                ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4===6?0:1) : 0)+ 

                ( feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5=== 6? 0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5===6?0:1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5===6?0:1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5===6?0:1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5 ?  (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5===6?0:1) : 0) ;
                
                var doctorScore = 0;
                totaldoctorentries === 0 ? doctorScore = 0 :  doctorScore = Math.round(((feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorcourtesyrating1): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorempathyrating1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorexplanationrating1): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorskillsrating1) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance1.doctorprofessionalrating1) : 0)

                +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorcourtesyrating2): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorempathyrating2): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorexplanationrating2): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorskillsrating2) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance2.doctorprofessionalrating2) : 0)

                +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorcourtesyrating3): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorempathyrating3): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorexplanationrating3): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorskillsrating3) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance3.doctorprofessionalrating3) : 0)

                +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorcourtesyrating4): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorempathyrating4): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorexplanationrating4): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorskillsrating4) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance4.doctorprofessionalrating4) : 0)

                +(feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorcourtesyrating5): 0 )+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorempathyrating5): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorexplanationrating5): 0) + (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorskillsrating5) : 0)+ (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5 ? (feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5=== 6? 0:feedbackItem.survey.generalsurvey.doctorrating.doctorperformance5.doctorprofessionalrating5) : 0)

                )/(totaldoctorentries)*100)/100;
                doctor_scores = doctor_scores + doctorScore;
                
    
               
                if (totaldoctorentries !== 0) num_feedbacks =num_feedbacks + 1;
            }
            } catch {
                continue;
            }

        }

        const averageScore = (doctor_scores + staff_scores) / num_feedbacks;

        return { average_score: averageScore , num_feedbacks: num_feedbacks }

    });


    return (
        <>

            <GeneralCard metricName="Employees" score={Math.round(score.average_score * 100) / 5} numFeedback={score.num_feedbacks}></GeneralCard>

        </>
    )
}

